### ISSUE TITLE
Eclipse becomes unresponsive when trying to refresh a viewer with more than 30000 elements on one level

### ISSUE THREAD

**Issue by raghucssit** [eclipse-platform/eclipse.platform.ui#818]
Description:
When we have a large number of files inside a folder in an eclipse workspace refreshing the folder makes the UI freeze.
Large number may depend on machine configuration. As per my test if we have ~30000 files generated on the disk and if we try to refresh the folder under project eclipse freezes. It takes more than 30 seconds to populate tree items in the **Package Explorer**.

The reason behind this is  viewer takes all the time to create Items.

Solution proposed: We will limit the number of Items created and add an Expandable Node. This Expandable Node on click populate next block of Limited elements with another Expandable Node. This way we can keep the Package Explorer responsive. 

The goal is to minimize the effort client need to use this solution. So client can implement **ILimitBasedContentProvider** with the existing content provider and tell us the number items to show in the viewer. **WrapperContentProvider** is an example and can be used to wrap existing Content Provider.

Below is the screenshot how does it look if we have items limit = 10 and number of files on the file system is 30000.
![partition-based-pe2](https://github.com/eclipse-platform/eclipse.platform.ui/assets/10301131/e1c8b14c-99bc-4486-b839-29d5743a21b2)

**Comment by iloveeclipse** [comment]
Note: the main goal here is to provide a small extension to viewers / content providers API that would allow every existing viewer implementation (Package / Project Explorer, JUnit, Search view etc) that can have a huge number of elements to deal with that huge number of elements without freezing UI **and** without lot of internal code rework.

As the end result we (Advantest) plan to provide patches for all affected SDK views that we are aware of and where we saw freezes.

**Comment by iloveeclipse** [comment]
Note: there are few things to do:

1) [x] After first SDK build is available, merge [JDT UI change](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/632) 
2) More tests & polishing if needed
3) Add help entry for the new preference
4) N&N with explanation what is possible what not, which limitations etc

**Comment by Phillipus** [comment]
Nice work.

I tested it on our RCP with a tree node containing about 10,000 children. I set `setDisplayIncrementally(5000)`. When I clicked on the expandable node the remaining 5000 child nodes seemed to be added one at a time and was very slow (I could see the tree's scroll bar moving). Is this a redraw problem?

**Comment by iloveeclipse** [comment]
> 5000 child nodes seemed to be added one at a time and was very slow (I could see the tree's scroll bar moving). Is this a redraw problem?

Hard to say, but I would just guess that's what needed by JFace/SWT to create and render the nodes. If it was on Windows, I found the limit of 1000 more appropriate, compared with Linux where 10.000 was OK. The strange thing is that creation on Windows is slower, but rendering on Linux is then the bigger issue.

**Comment by iloveeclipse** [comment]
BTW, for testing with different use cases see  also https://github.com/eclipse-platform/eclipse.platform.ui/pull/810 description where you can try different "kinds" of slowness.

**Comment by iloveeclipse** [comment]
> Nice work.

Yea, it was mostly hard work of @raghucssit, so kudos to him.

**Comment by Phillipus** [comment]
> Yea, it was mostly hard work of @raghucssit, so kudos to him.

Indeed. It does a great job and could be useful for our RCP app where a tree node might have many thousands of child nodes.

**Comment by iloveeclipse** [comment]
I've tried now to disable redraw during element creation after the click on the expandable node, but that didn't make things better, I got no feedback at all in UI and UI was not faster rendering elements, so I guess it's Jface/SWT code that needs this time to create elements. But I haven't used profiler, feel free to double check it. May be there is some optimization possible.

Patch:
```
diff --git a/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/TableViewer.java b/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/TableViewer.java
index 037c8ed..535efec 100644
--- a/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/TableViewer.java
+++ b/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/TableViewer.java
@@ -478,7 +478,17 @@
 
 		if (nextChildren.length > 0) {
-			// create remaining elements
-			for (Object nextChild : nextChildren) {
-				createItem(nextChild, -1);
+			Control control = getControl();
+			if (control != null) {
+				control.setRedraw(false);
+			}
+			try {
+				// create remaining elements
+				for (Object nextChild : nextChildren) {
+					createItem(nextChild, -1);
+				}
+			} finally {
+				if (control != null) {
+					control.setRedraw(true);
+				}
 			}
 			// If we've expanded but still have not reached the limit
diff --git a/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/TreeViewer.java b/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/TreeViewer.java
index 78e3292..7c5db52 100644
--- a/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/TreeViewer.java
+++ b/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/TreeViewer.java
@@ -1156,10 +1156,18 @@
 		disassociate(item);
 		item.dispose();
-
-		// create children on parent
-		for (Object element : children) {
-			createTreeItem(parent, element, -1);
+		Control control = getControl();
+		if (control != null) {
+			control.setRedraw(false);
 		}
-
+		try {
+			// create children on parent
+			for (Object element : children) {
+				createTreeItem(parent, element, -1);
+			}
+		} finally {
+			if (control != null) {
+				control.setRedraw(true);
+			}
+		}
 		if (children.length > 0) {
 			// If we've expanded but still have not reached the limit
```

**Comment by Phillipus** [comment]
> so I guess it's Jface/SWT code that needs this time to create elements.

I guess so. I'll have to dig deeper, unless @raghucssit can offer insight.

FWIW, my use case is that opening a tree node with 10,000 or more child nodes is slow, but 5,000 is OK. But opening 5,000 nodes initially then clicking on the expandable node for the other 5,000 is a lot slower than just opening the 10,000 in one go.

Not a complaint, BTW, just an observation. :-)

**Comment by jukzi** [comment]
Feature missing (or not working?) in Git Repositories/Git Staging view. That feels inconsistent.

Note that Git History has it's own hard cap
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/3f7fa524-fcf8-4663-8f61-62b146e31903)

**Comment by iloveeclipse** [comment]
> That feels inconsistent.

This is something we as "platform provider" can't fix because we don't ship a single "product".

The feature just provides **API** to use for clients, because switching it on by default may break client code.
For now it is enabled in Package and Project explorers, Java Editor Breadcrumb and Outline, Problems and Search views.

So every client that sees a problem with potentially huge number of elements needs (small) code adoption.

**Comment by jukzi** [comment]
For search view a default limit of 1000 is far too small, as discussed in https://github.com/eclipse-platform/eclipse.platform.text/pull/184#discussion_r1179132698

**Comment by iloveeclipse** [comment]
> I guess so. I'll have to dig deeper, unless @raghucssit can offer insight.

@Phillipus : see #1016 and [this comment](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1016#issuecomment-1679193634). At least on Linux tree creation/incremental update times are similar for same number of elements. Are you on Windows or Mac?

**Comment by Phillipus** [comment]
> @Phillipus : see #1016 and [this comment](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1016#issuecomment-1679193634). At least on Linux tree creation/incremental update times are similar for same number of elements. Are you on Windows or Mac?

Windows. For every tree creation/update I see the scroll bar of the TreeViewer move, suggesting a notification to the UI.

**Comment by iloveeclipse** [comment]
Hmm. Can you please try https://github.com/eclipse-platform/eclipse.platform.ui/pull/1018 with `setRedraw()` applied to the tree too (we haven't seen any effect on Linux and I also didn't noticed anything on Windows)?

**Comment by Phillipus** [comment]
> Hmm. Can you please try #1018 with `setRedraw()` applied to the tree too (we haven't seen any effect on Linux and I also didn't noticed anything on Windows)?

#1018 didn't make any difference but adding `getTree().setRedraw(false)` and `getTree().setRedraw(true);` to the start and end of `handleExpandableNodeClicked` made a big improvement in speed, and the scroll bar doesn't move.

**Comment by Phillipus** [comment]
Some timings on a node with 10000 child nodes and `TreeViewer#setDisplayIncrementally(5000)`

To display the first 5000 child nodes when expanding parent node, `AbstractTreeViewer#createChildren` takes about 120 ms.

To display the remaining 5000 nodes `TreeViewer#handleExpandableNodeClicked` takes 11400 ms.

To display the remaining 5000 nodes with `getTree().setRedraw(false)` `TreeViewer#handleExpandableNodeClicked` takes 2100 ms.

Windows 11

**Comment by Phillipus** [comment]
The above timings were on a real-world example in our RCP app. To test with a snippet try this:

```java
package com.archimatetool.editor;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.jface.viewers.ITreeContentProvider;
import org.eclipse.jface.viewers.LabelProvider;
import org.eclipse.jface.viewers.TreeViewer;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Tree;
import org.eclipse.swt.widgets.TreeColumn;

public class TreeViewerTest {

    private static class MyContentProvider implements ITreeContentProvider {
        @Override
        public Object[] getElements(Object inputElement) {
            return ((MyModel)inputElement).children.toArray();
        }

        @Override
        public Object[] getChildren(Object parentElement) {
            return getElements(parentElement);
        }

        @Override
        public Object getParent(Object element) {
            if(element == null) {
                return null;
            }

            return ((MyModel)element).parent;
        }

        @Override
        public boolean hasChildren(Object element) {
            return ((MyModel)element).children.size() > 0;
        }

    }

    public static class MyModel {
        public MyModel parent;
        public int count;
        public List<MyModel> children = new ArrayList<>();

        public MyModel(MyModel parent, int count) {
            this.parent = parent;
            this.count = count;
        }
        
        @Override
        public String toString() {
            return "Item " + (count + 1);
        }
    }

    public TreeViewerTest(Shell shell) {
        final TreeViewer v = new TreeViewer(shell);
        v.setLabelProvider(new LabelProvider());
        v.setDisplayIncrementally(5000);
        v.setContentProvider(new MyContentProvider());
        createColumn(v.getTree(), "Column");
        v.setInput(createModel());
    }

    public void createColumn(Tree tr, String text) {
        TreeColumn column = new TreeColumn(tr, SWT.NONE);
        column.setWidth(100);
        column.setText(text);
        tr.setHeaderVisible(true);
    }

    private MyModel createModel() {
        MyModel root = new MyModel(null, -1);
        
        MyModel m = new MyModel(root, -1);
        root.children.add(m);
        
        for(int i = 0; i < 10000; i++) {
            MyModel n = new MyModel(m, i);
            m.children.add(n);
        }

        return root;
    }

    public static void main(String[] args) {
        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setLayout(new FillLayout());
        new TreeViewerTest(shell);
        shell.open();

        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) display.sleep();
        }

        display.dispose();
    }
}
```

**Comment by jukzi** [comment]
Given the amount of problems i saw when using a softlimit for some hours [1], i suggest to disable the feature by default with a value of 0 and start M1 with a ridiculous low default value of 10 so that more people are forced to test it. That would also allow your users to test it by manually enabling the feature. When all problems solved we should discuss the final default value(s).
If the API may need changes to fix issues, i suggest to mark it as Provisional - see https://wiki.eclipse.org/Provisional_API_Guidelines - which may need a PMC decision @vogella  @akurtakov 

I really like the idea of the feature, and want to thank Advantest for all the effort. It just doesn't feel ready for production yet.

[1] https://github.com/eclipse-platform/eclipse.platform.ui/issues?q=is%3Aissue+SoftLimit

**Comment by akurtakov** [comment]
Given the amount of issues (and especially https://github.com/eclipse-platform/eclipse.platform.ui/issues/1014 ) I agree with jukzi that it's not ready for prime time and it would better be improved for December release before being enabled by default. 
@tjwatson @theMcQ @jarthana @merks  - please share your opinions.

**Comment by akurtakov** [comment]
What troubles me most is that https://github.com/eclipse-platform/eclipse.platform.ui/issues/1027  is yet another representation of https://github.com/eclipse-platform/eclipse.platform.ui/issues/1008 and that this issue will pop up pretty much everywhere limits are shown.

**Comment by akurtakov** [comment]
@jukzi Please add links to all issues you open about softlimit so there is all the information here.

**Comment by laeubi** [comment]
By the way it might be good when clicking on the expandable node to show a progress wheel on start of `handleExpandableNodeClicked` and process the event queue after e.g. every 100 items processed...

**Comment by laeubi** [comment]
@akurtakov https://github.com/eclipse-platform/eclipse.platform.ui/issues?q=is%3Aopen+is%3Aissue+author%3Ajukzi+softlimit

**Comment by iloveeclipse** [comment]
Sure, we can set the preference to zero to disable the feature for M3 nd mark API as provisional.
@raghucssit : please prepare PR.

**Comment by raghucssit** [comment]
> Sure, we can set the preference to zero to disable the feature for M3 nd mark API as provisional. @raghucssit : please prepare PR.

ok. i will work on it.

**Comment by iloveeclipse** [comment]
Update: so far all known bugs were fixed and by default feature will be not enabled in M3 (preference need to be manually changed by used to enable the feature).

We (Advantest) will continue working on enabling this feature in 4.29 and on implementing reported enhancement requests. Everyone is welcome to help of course :-)

**Comment by Phillipus** [comment]
Thank-you everyone involved for your work and for listening to the community. :-)

**Comment by vogella** [comment]
Could you also add it to the N&N of 4.29 / 4.30 and describe how to enable it in the preferences? Otherwise it is impossible for users to find out of this new feature.

**Comment by vogella** [comment]
Ping for N&N entry. Without this entry it is almost for other projects to leverage this improvement in their viewers.

**Comment by vogella** [comment]
If I create a new project with 30 000 and open it in the project explorer it still freezes for a very long time.
@iloveeclipse you said it is already implemented in project explorer but as @raghucssit  never responded to the request to document this feature in the N&N I don't see how to activate it.

Here is my test handler to generate example project.

```
package com.vogella.resources.handlers;

import java.io.ByteArrayInputStream;
import java.util.Random;

import org.eclipse.core.filesystem.EFS;
import org.eclipse.core.filesystem.IFileStore;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IFolder;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.resources.IWorkspace;
import org.eclipse.core.resources.IWorkspaceRoot;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.NullProgressMonitor;
import org.eclipse.e4.core.di.annotations.Execute;
import org.eclipse.ui.IWorkbenchPage;

public class CreateLargeProjectHandler {
	private final Random random = new Random();

	private static final String CHARSFORCREATION = "abcdefghijklmnopqrstuvwxyz";

	@Execute
	public void execute(IWorkbenchPage page) {
		IWorkspace workspace = ResourcesPlugin.getWorkspace();
		IWorkspaceRoot root = workspace.getRoot();
		IProject project = root.getProject("performancetest");
		try {
			project.create(new NullProgressMonitor());
			project.open(null);
			for (int i = 0; i < 1; i++) {
				IFolder folder = project.getFolder("test" + i);
				folder.create(true, true, null);
				for (int j = 0; j < 30000; j++) {
					IFile file = folder.getFile(createString(10));
					file.create(new ByteArrayInputStream(createBytes(5000)), IResource.NONE, null);
					IFileStore fileStore = EFS.getLocalFileSystem().getStore(file.getFullPath());
					if (!fileStore.fetchInfo().isDirectory()) {
//						try {
//							IDE.openEditorOnFileStore(page, fileStore);
//						} catch (PartInitException e) {
//							/* some code */
//						}
					}
				}
			}
		} catch (CoreException e) {
			// nothing to do
		}
	}

	private byte[] createBytes(int length) {
		byte[] bytes = new byte[length];
		random.nextBytes(bytes);
		return bytes;
	}

	private String createString(int length) {
		StringBuilder buf = new StringBuilder(length);
		// fill the string with random characters up to the desired length
		for (int i = 0; i < length; i++) {
			buf.append(CHARSFORCREATION.charAt(random.nextInt(CHARSFORCREATION.length())));
		}
		return buf.toString();
	}

}
```

**Comment by iloveeclipse** [comment]
> If I create a new project with 30 000 and open it in the project explorer it still freezes for a very long time.

See #1425, the feature was disabled by default.

**Comment by iloveeclipse** [comment]
N&N for 4.31 were added via https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/104 .
With that and #1425 we are done for the main part of the ticket. 
Whatever enhancement requests or bugs can be found, should go to dedicated tickets.
